In [127]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [128]:
car='/home/amador/Desktop/backup/dados/base_car.csv'
df=pd.read_csv(car)

In [129]:
df.head(12)

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7

In [130]:
df.columns

Index(['Car Model', 'Mileage', 'Sell Price($)', 'Age(yrs)'], dtype='object')

In [131]:
# alterando nome das colunas
df.columns=['modelo','mileage','price','age_yrs']

### Label Encoder e One Hot Encoding

In [132]:
# aplicando LabelEncoder
le=LabelEncoder()
df_le=df.copy()
df_le.modelo=le.fit_transform(df_le.modelo)
df_le

modelo  mileage  price  age_yrs
0        1    69000  18000        6
1        1    35000  34000        3
2        1    57000  26100        5
3        1    22500  40000        2
4        1    46000  31500        4
5        0    59000  29400        5
6        0    52000  32000        5
7        0    72000  19300        6
8        0    91000  12000        8
9        2    67000  22000        6
10       2    83000  20000        7
11       2    79000  21000        7
12       2    59000  33000        5

In [133]:
# transformando df em array
# somente para exemplificar --> pode ser pego somente a coluna (ou colunas) que será usada para a transformação
# exemplo df_le['modelo'].values
df_array=df_le.values
type(df_array)

numpy.ndarray

In [134]:
# Visualizando coluna de preços
df_array[:][:,2]

array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
       22000, 20000, 21000, 33000])

In [135]:
# Visualizando coluna carros
df_array[:][:,0]

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [136]:
# aplicando one hot encoding
# criando o objeto one hot encoding
ohe=OneHotEncoder()
# pegando a coluna como array
modelo_array=df_le['modelo'].values
# pegando o tamanho da coluna e fazendo reshape de 13x1
inteiros=modelo_array.reshape(len(modelo_array),1)
inteiros.shape


(13, 1)

In [137]:
# Criando as novas features a partir da matriz de presença
novas_features = ohe.fit_transform(inteiros)
# tipo das novas features
type(novas_features)

scipy.sparse.csr.csr_matrix

In [138]:
# Concatenando as novas features ao array em formato array
dataset_array = np.concatenate([df_array, novas_features.toarray()], axis=1)
# visualizando shape
dataset_array.shape

(13, 7)

In [139]:
# Transformando em dataframe e visualiza as colunas
dataf = pd.DataFrame(dataset_array)

In [140]:
dataf.head(13)

0        1        2    3    4    5    6
0   1.0  69000.0  18000.0  6.0  0.0  1.0  0.0
1   1.0  35000.0  34000.0  3.0  0.0  1.0  0.0
2   1.0  57000.0  26100.0  5.0  0.0  1.0  0.0
3   1.0  22500.0  40000.0  2.0  0.0  1.0  0.0
4   1.0  46000.0  31500.0  4.0  0.0  1.0  0.0
5   0.0  59000.0  29400.0  5.0  1.0  0.0  0.0
6   0.0  52000.0  32000.0  5.0  1.0  0.0  0.0
7   0.0  72000.0  19300.0  6.0  1.0  0.0  0.0
8   0.0  91000.0  12000.0  8.0  1.0  0.0  0.0
9   2.0  67000.0  22000.0  6.0  0.0  0.0  1.0
10  2.0  83000.0  20000.0  7.0  0.0  0.0  1.0
11  2.0  79000.0  21000.0  7.0  0.0  0.0  1.0
12  2.0  59000.0  33000.0  5.0  0.0  0.0  1.0

In [141]:
# renomeando as colunas do df
dataf.columns=['modelo','Mileage','price','age_yrs','car1','car2','car3']
dataf.head()

modelo  Mileage    price  age_yrs  car1  car2  car3
0     1.0  69000.0  18000.0      6.0   0.0   1.0   0.0
1     1.0  35000.0  34000.0      3.0   0.0   1.0   0.0
2     1.0  57000.0  26100.0      5.0   0.0   1.0   0.0
3     1.0  22500.0  40000.0      2.0   0.0   1.0   0.0
4     1.0  46000.0  31500.0      4.0   0.0   1.0   0.0

In [142]:
# dropando a coluna original
dataf.drop(['modelo'],axis=1,inplace=True)
dataf

Mileage    price  age_yrs  car1  car2  car3
0   69000.0  18000.0      6.0   0.0   1.0   0.0
1   35000.0  34000.0      3.0   0.0   1.0   0.0
2   57000.0  26100.0      5.0   0.0   1.0   0.0
3   22500.0  40000.0      2.0   0.0   1.0   0.0
4   46000.0  31500.0      4.0   0.0   1.0   0.0
5   59000.0  29400.0      5.0   1.0   0.0   0.0
6   52000.0  32000.0      5.0   1.0   0.0   0.0
7   72000.0  19300.0      6.0   1.0   0.0   0.0
8   91000.0  12000.0      8.0   1.0   0.0   0.0
9   67000.0  22000.0      6.0   0.0   0.0   1.0
10  83000.0  20000.0      7.0   0.0   0.0   1.0
11  79000.0  21000.0      7.0   0.0   0.0   1.0
12  59000.0  33000.0      5.0   0.0   0.0   1.0

### Get Dummies

In [143]:
df.head(3)

modelo  mileage  price  age_yrs
0  BMW X5    69000  18000        6
1  BMW X5    35000  34000        3
2  BMW X5    57000  26100        5

In [144]:
dummies=pd.get_dummies(df.modelo,prefix='car') #prefixo é opcional
dummies

car_Audi A5  car_BMW X5  car_Mercedez Benz C class
0             0           1                          0
1             0           1                          0
2             0           1                          0
3             0           1                          0
4             0           1                          0
5             1           0                          0
6             1           0                          0
7             1           0                          0
8             1           0                          0
9             0           0                          1
10            0           0                          1
11            0           0                          1
12            0           0                          1

In [145]:
# atribuindo ao df
merged=pd.concat([df,dummies],axis=1) # pode ser axis=columns
merged

modelo  mileage  price  age_yrs  car_Audi A5  car_BMW X5  \
0                  BMW X5    69000  18000        6            0           1   
1                  BMW X5    35000  34000        3            0           1   
2                  BMW X5    57000  26100        5            0           1   
3                  BMW X5    22500  40000        2            0           1   
4                  BMW X5    46000  31500        4            0           1   
5                 Audi A5    59000  29400        5            1           0   
6                 Audi A5    52000  32000        5            1           0   
7                 Audi A5    72000  19300        6            1           0   
8                 Audi A5    91000  12000        8            1           0   
9   Mercedez Benz C class    67000  22000        6            0           0   
10  Mercedez Benz C class    83000  20000        7            0           0   
11  Mercedez Benz C class    79000  21000        7            0           0   
12  Mercedez Benz C class    59000  33000        5            0           0   

    car_Mercedez Benz C class  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  
5                           0  
6                           0  
7                           0  
8                           0  
9                           1  
10                          1  
11                          1  
12                          1

In [146]:
get=merged.drop(['modelo','car_Audi A5'],axis='columns')
get
# observação: Ao fazer o get dummies, se exclui uma das categorias para evitar o efeito da multicolinearidade.
# logo se são 3 categorias, tem-se que excluir uma.
# Multicolinearidade consiste em um problema comum em regressões, no qual as variáveis independentes possuem relações lineares exatas ou aproximadamente exatas.

mileage  price  age_yrs  car_BMW X5  car_Mercedez Benz C class
0     69000  18000        6           1                          0
1     35000  34000        3           1                          0
2     57000  26100        5           1                          0
3     22500  40000        2           1                          0
4     46000  31500        4           1                          0
5     59000  29400        5           0                          0
6     52000  32000        5           0                          0
7     72000  19300        6           0                          0
8     91000  12000        8           0                          0
9     67000  22000        6           0                          1
10    83000  20000        7           0                          1
11    79000  21000        7           0                          1
12    59000  33000        5           0                          1

## DataFrames
##### * get= get dummies
##### * dataf= Le e OHE

## Utilizando o GET

In [147]:
# criando objeto para regressão linear
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [148]:
# separando colunas
X=get.drop('price',axis=1)
y=get.price
X

mileage  age_yrs  car_BMW X5  car_Mercedez Benz C class
0     69000        6           1                          0
1     35000        3           1                          0
2     57000        5           1                          0
3     22500        2           1                          0
4     46000        4           1                          0
5     59000        5           0                          0
6     52000        5           0                          0
7     72000        6           0                          0
8     91000        8           0                          0
9     67000        6           0                          1
10    83000        7           0                          1
11    79000        7           0                          1
12    59000        5           0                          1

In [149]:
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: price, dtype: int64

In [150]:
# treinando o modelo
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [151]:
# predizendo resultados
# mileage 	age_yrs 	car_BMW X5 	car_Mercedez Benz C class
model.predict([[22000,5,0,1],[200,5,0,1],[22000,5,1,0],[200,5,1,0]])

array([44171.67175393, 52240.3334116 , 37433.46442827, 45502.12608594])

In [152]:
model.score(X,y)

0.9417050937281082

## Utilizando o dataf

In [153]:
# separando colunas
X2=dataf.drop('price',axis=1)
y2=dataf.price
X2

Mileage  age_yrs  car1  car2  car3
0   69000.0      6.0   0.0   1.0   0.0
1   35000.0      3.0   0.0   1.0   0.0
2   57000.0      5.0   0.0   1.0   0.0
3   22500.0      2.0   0.0   1.0   0.0
4   46000.0      4.0   0.0   1.0   0.0
5   59000.0      5.0   1.0   0.0   0.0
6   52000.0      5.0   1.0   0.0   0.0
7   72000.0      6.0   1.0   0.0   0.0
8   91000.0      8.0   1.0   0.0   0.0
9   67000.0      6.0   0.0   0.0   1.0
10  83000.0      7.0   0.0   0.0   1.0
11  79000.0      7.0   0.0   0.0   1.0
12  59000.0      5.0   0.0   0.0   1.0

In [154]:
y2

0     18000.0
1     34000.0
2     26100.0
3     40000.0
4     31500.0
5     29400.0
6     32000.0
7     19300.0
8     12000.0
9     22000.0
10    20000.0
11    21000.0
12    33000.0
Name: price, dtype: float64

In [155]:
# criando objeto para regressão linear
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [156]:
# treinando o modelo
model.fit(X2,y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [157]:
# predizendo resultados
# Mileage 	age_yrs 	car1  (Audi A5)	car2 (car_BMW X5)	car3 (car_Mercedez Benz)

model.predict([[22000,5,1,0,0],[200,5,1,0,0],[22000,5,0,1,0],[200,5,0,1,0],[22000,5,0,0,1],[200,5,0,0,1]])

array([41718.13101667, 49786.79267434, 37433.46442827, 45502.12608594,
       44171.67175393, 52240.3334116 ])

In [158]:
model.score(X2,y2)

0.9417050937281082